- hosts: all
  user: root
  become: True
  vars_files:
    - ../vars/bashrc.yml
  vars:
    bashrc_file: |
      export {{ master_bashrc }}
      export {{ osd_nodes_bashrc }}
      export {{ monitors_bashrc }}
  tasks:
    - name: bashrc
      copy: 
        content: "{{ bashrc_file }}"
        dest: "{{item.dest}}"
        owner: "{{item.owner}}" 
        group: "{{item.group}}"
        mode: 0644
      with_items:
        - {dest: /root/.bashrc, owner: root, group: root}
        - {dest: /home/cbt/.bashrc, owner: cbt, group: cbt}
