- hosts: all
  user: root
  become: True
  vars_files:
    - ../vars/cbt_user.yml
  tasks:
    - name: create cbt group
      group:
        name: cbt
        state: present
    - name: create cbt user
      user: 
        name: cbt
        group: cbt
        password: cbt
        shell: /bin/bash
        state: present
    - name: sudo without password for cbt user
      copy:
        content: 'cbt ALL=(ALL) NOPASSWD:ALL'
        dest: /etc/sudoers.d/cbt
        mode: '0440'
