- hosts: osdnodes
  user: root
  become: True
  tasks:
    - name: prepare disks
      script: ../scripts/prepare_disks.sh

- hosts: all
  user: root
  become: True
  tasks:
    - name: reboot servers
      reboot:

- hosts: master
  user: root
  tasks:
    - name: mount /dev/sdb1 on master
      command: mount /dev/sdb1 /opt

    - name: Recursively change ownership of /opt/cbt directory
      file:
        path: /opt/cbt
        state: directory
        recurse: yes
        owner: cbt
        group: cbt

