#- hosts: osdnodes
#  user: root
#  become: True
#  tasks:
#    - name: create partlabels symlinks
#      script: ../scripts/create_partlabels_symlinks_ses7.sh

- hosts: master
  user: root
  become: True
  tasks:
    - name: create /opt/cbt/ceph_cbt.conf file
      become_user: cbt
      script: ../scripts/create_ceph_cbt_conf.sh
