- name: Exchange Keys between servers
  hosts: all
  become: True
  vars_files:
    - ../vars/ssh_access.yml
  tasks:
    - name: SSH KeyGen command
      tags: run
      become_user: cbt
      shell: >
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"

    - name: Fetch the keyfile from the node to master
      tags: run
      become_user: cbt
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{ansible_fqdn}}-id_rsa.pub"
        flat: yes

    - name: Copy the key add to authorized_keys using Ansible module
      tags: runcd
      authorized_key:
        user: cbt
        state: present
        key: "{{ lookup('file','buffer/{{item}}-id_rsa.pub')}}"
      when: item != ansible_fqdn
      with_items:
        - "{{ groups['all'] }}"

    - name: create ssh config
      copy:
        dest: /home/cbt/.ssh/config
        content: "{{ ssh_config }}"
        owner: cbt
        group: cbt
        mode: '0644'
