- name: Exchange Keys between servers
  hosts: all
  become: True
  vars_files:
    - ../vars/ssh_access.yml
  tasks:
    - name: SSH KeyGen command
      tags: run
      become_user: "{{ item }}"
      shell: >
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
      loop: "{{users}}"

    - name: Fetch the keyfile from the node to master
      tags: run
      become_user: "{{ item }}"
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "buffer/{{ item }}-{{ansible_fqdn}}-id_rsa.pub"
        flat: yes
      loop: "{{users}}"

    - name: Copy the key add to authorized_keys for root user
      tags: runcd
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file','buffer/root-{{item}}-id_rsa.pub')}}"
      when: item != ansible_fqdn
      with_items:
        - "{{ groups['all'] }}"

    - name: Copy the key add to authorized_keys for cbt user
      tags: runcd
      authorized_key:
        user: cbt
        state: present
        key: "{{ lookup('file','buffer/cbt-{{item}}-id_rsa.pub')}}"
      when: item != ansible_fqdn
      with_items:
        - "{{ groups['all'] }}"

    - name: create ssh config
      become_user: "{{item}}"
      copy:
        dest: ~/.ssh/config
        content: "{{ ssh_config }}"
        owner: "{{item}}"
        group: "{{item}}"
        mode: '0644'
      loop: "{{users}}"
